### PR TITLE
Testing (fix - or at least move forward - bookworm compat)

### PR DESCRIPTION
**Pull request by alexAubin**

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
```
157320 INFO    DEBUG - ln -sf /var/www/photoview/libheif/examples/../go /var/www/photoview/libheif/examples/src/github.com/strukturag/libheif/
157320 INFO    DEBUG - GOPATH=/var/www/photoview/libheif/examples PKG_CONFIG_PATH=:/var/www/photoview/libheif:/var/www/photoview/libheif/libde265/dist/lib/pkgconfig/ CGO_CFLAGS="-I/var/www/photoview/libheif" CGO_LDFLAGS="-L/var/www/photoview/libheif/libheif/.libs" LD_LIBRARY_PATH=/var/www/photoview/libheif/libheif/.libs /usr/bin/go build -o heif-test-go heif-test.go

157320 INFO    DEBUG - heif-test.go:39:2: no required module provides package github.com/strukturag/libheif/go/heif: go.mod file not found in current directory or any parent directory; see 'go help modules'

157320 INFO    DEBUG - make[2]: *** [Makefile:1204: heif-test-go] Error 1
157320 INFO    DEBUG - make[2]: Leaving directory '/var/www/photoview/libheif/examples'
157320 INFO    DEBUG - make[1]: *** [Makefile:538: all-recursive] Error 1
157320 INFO    DEBUG - make[1]: Leaving directory '/var/www/photoview/libheif'
157320 INFO    DEBUG - make: *** [Makefile:447: all] Error 2
```

@_@

**Comment by ericgaspar** [comment]
!testme

**Comment by Salamandar** [comment]
!testme

**Pull request merged**
